doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App/Product:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Product/Infrastructure/Persistence/Mysql'
                prefix: 'App\Product\Infrastructure\Persistence\Mysql'
                alias: App
            App/Catalog:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Catalog/Infrastructure/Persistence/Mysql'
                prefix: 'App\Catalog\Infrastructure\Persistence\Mysql'
                alias: App
            App/Cart:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Cart/Infrastructure/Persistence/Mysql'
                prefix: 'App\Cart\Infrastructure\Persistence\Mysql'
                alias: App
