version: '3.7'
services:
  php:
    image: shopping_cart_application:latest
    volumes:
      - .:/var/www/html:cached
      - ~/.ssh:/home/docker/.ssh:cached
      - ./config/apache2/docker-php.conf:/etc/apache2//conf-available/docker-php.conf:cached
    environment:
      PHP_EXTENSION_XDEBUG: 1
      PHP_INI_XDEBUG__REMOTE_PORT: 9000
      PHP_INI_XDEBUG__REMOTE_HOST: 10.254.254.254
#      XDEBUG_CONFIG: "remote_port=9000 remote_autostart=1"
  ngnix:
    image: nginx:1.17
    volumes:
      - .:/var/www/html:cached
      - /Users/Dawid/www/shopping_cart_application/config/nginx/site2.conf:/etc/nginx/conf.d/site2.conf
      - /Users/Dawid/www/shopping_cart_application/config/apache2/docker-php.conf:/etc/nginx/conf.d/site3.conf
    ports:
      - "80:80"
    depends_on:
      - php
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
#    command: --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    networks:
      network:
        ipv4_address: 10.20.0.3
  test_mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
#    command: --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    networks:
      network:
        ipv4_address: 10.20.0.4

networks:
  network:
    ipam:
      config:
        - subnet: 10.20.0.0/24